GET http://localhost:5000/proxi-users/users/

###

GET http://localhost:5000/proxi-users/phoneNumber/%28508%29%20615-7464

###

GET http://localhost:5000/events/all-events

###

POST http://localhost:5000/proxi-users/register 
Content-Type: application/json

{
    "phoneNumber": "(774) 818-1234"
}

###

POST http://localhost:5000/events/register 
Content-Type: application/json

{
    "name": "Introduction to UI/UX",
    "location": "Boston",
    "date": "Apr 21 2023",
    "description": "Visual designers make websites look beautiful. UX/UI designers make them work. Go behind the scenes in this free crash course as we explore the day-to-day of the role, the skills you'll need, and how to launch a career in this lucrative field.\n\nWe'll walk you through how to get the skills to become a top-notch designer yourself and highlight the path to getting those various jobs that will be open to you once you've mastered this skill set.",
    "joinCode": "123456",
    "imageSource": "https://cdn-az.allevents.in/events5/banners/e5db97533141c27ce07946203474b08ae8a69aa9b37cd289ae54d5a08740f354-rimg-w1200-h675-gmir.jpg?v=1669835614"
}

###

POST http://localhost:5000/events/register 
Content-Type: application/json

{
    "name": "Software Product Exposition",
    "location": "Boston",
    "date": "Apr 24 2023",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet enim tortor at auctor urna nunc id. Eget gravida cum sociis natoque. Sociis natoque penatibus et magnis. Natoque penatibus et magnis dis parturient montes nascetur. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Non diam phasellus vestibulum lorem sed. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Arcu dictum varius duis at consectetur lorem donec. Placerat duis ultricies lacus sed turpis tincidunt.",
    "joinCode": "654321",
    "imageSource": "https://spotme.com/wp-content/uploads/2021/03/virtual-product-launch-event-examples.jpg"
}

###

POST http://localhost:5000/events/register 
Content-Type: application/json

{
    "name": "Amazon Web Fair",
    "location": "Seattle, WA",
    "date": "May 3 2023",
    "description": "Elit ut aliquam purus sit. Id venenatis a condimentum vitae sapien pellentesque. Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Elit eget gravida cum sociis natoque penatibus et magnis. Diam vel quam elementum pulvinar etiam non quam lacus suspendisse. Fermentum iaculis eu non diam phasellus vestibulum lorem. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Nisl vel pretium lectus quam id leo in. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Est ante in nibh mauris. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Eget arcu dictum varius duis at consectetur lorem. Justo laoreet sit amet cursus sit amet. At quis risus sed vulputate odio ut enim blandit volutpat.",
    "joinCode": "456123",
    "imageSource": "https://www.the-sun.com/wp-content/uploads/sites/6/2022/02/NINTCHDBPICT000561981244.jpg?w=620"
}

###

POST http://localhost:5000/events/register 
Content-Type: application/json

{
    "name": "Google Career Event",
    "location": "San Francisco, CA",
    "date": "May 1 2023",
    "description": "In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Eu consequat ac felis donec et. Tellus rutrum tellus pellentesque eu tincidunt. Phasellus vestibulum lorem sed risus. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Sit amet purus gravida quis blandit turpis. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Ipsum suspendisse ultrices gravida dictum fusce. Tristique magna sit amet purus gravida quis. Sed risus ultricies tristique nulla aliquet enim tortor. Varius sit amet mattis vulputate enim. Euismod in pellentesque massa placerat duis ultricies lacus sed. Suspendisse potenti nullam ac tortor vitae. Bibendum neque egestas congue quisque egestas diam in arcu. Justo eget magna fermentum iaculis eu non.",
    "joinCode": "162534",
    "imageSource": "https://1000logos.net/wp-content/uploads/2021/05/Google-logo.png"
}

###

PUT http://localhost:5000/proxi-users/update/%28774%29%20818-1234
Content-Type: application/json

{
    "fullName": "Selwyn George",
    "jobTitle": "Student",
    "company": "Northeastern University",
    "location": "Boston, MA"
}

###

PUT http://localhost:5000/proxi-users/add-pending-connection/%28508%29%20615-7464
Content-Type: application/json

{
  "connectionId": "64418b27d126ddbac06a37bb"
}

### Add an event to the registered list

PUT http://localhost:5000/proxi-users/add-registered-event/%28508%29%20615-7464
Content-Type: application/json

{
  "eventId": "643eebcfed3d718ca749d9fe"
}

### Delete an event from the registered list

PUT http://localhost:5000/proxi-users/delete-registered-event/%28508%29%20615-7464
Content-Type: application/json

{
  "eventId": "643eebcfed3d718ca749d9fe"
}

### Add an event to the past events list

PUT http://localhost:5000/proxi-users/add-past-event/%28508%29%20615-7464
Content-Type: application/json

{
  "eventId": "643e189e56f5d5342b0c0c50"
}

###

GET http://localhost:5000/proxi-users/user/643d38c9f0325122c5b6bf7e


###

# Thomas: 643d3e511b8c63707d38ad60, Evan: 643d3e841b8c63707d38ad68, Selwyn: 643d38c9f0325122c5b6bf7e

PUT http://localhost:5000/proxi-users/add-connection/%28508%29%20615-7464
Content-Type: application/json

{
  "connectionId": "6441871dd126ddbac06a36c1"
}

### 

PUT http://localhost:5000/proxi-users/add-skills/%28508%29%20615-7464
Content-Type: application/json

{
  "skills": ["JavaScript", "React", "Node.js"]
}