GET http://localhost:5000/proxi-users/users/

###

GET http://localhost:5000/proxi-users/phoneNumber/%28508%29%20615-7464

###

GET http://localhost:5000/events/all-events

###

POST http://localhost:5000/proxi-users/register 
Content-Type: application/json

{
    "phoneNumber": "(774) 818-1234"
}

###

POST http://localhost:5000/events/register 
Content-Type: application/json

{
    "name": "Introduction to UI/UX",
    "location": "Boston",
    "date": "Apr 21 2023",
    "description": "Visual designers make websites look beautiful. UX/UI designers make them work. Go behind the scenes in this free crash course as we explore the day-to-day of the role, the skills you'll need, and how to launch a career in this lucrative field.\n\nWe'll walk you through how to get the skills to become a top-notch designer yourself and highlight the path to getting those various jobs that will be open to you once you've mastered this skill set.",
    "joinCode": "123456",
    "imageSource": "https://cdn-az.allevents.in/events5/banners/e5db97533141c27ce07946203474b08ae8a69aa9b37cd289ae54d5a08740f354-rimg-w1200-h675-gmir.jpg?v=1669835614"
}

###

PUT http://localhost:5000/proxi-users/update/%28774%29%20818-1234
Content-Type: application/json

{
    "fullName": "Selwyn George",
    "jobTitle": "Student",
    "company": "Northeastern University",
    "location": "Boston, MA"
}

###

PUT http://localhost:5000/proxi-users/add-pending-connection/%28508%29%20615-7464
Content-Type: application/json

{
  "connectionId": "643ee527e3d9a18acdfa46ea"
}

### Add an event to the registered list

PUT http://localhost:5000/proxi-users/add-registered-event/%28508%29%20615-7464
Content-Type: application/json

{
  "eventId": "643eebcfed3d718ca749d9fe"
}

### Delete an event from the registered list

PUT http://localhost:5000/proxi-users/delete-registered-event/%28508%29%20615-7464
Content-Type: application/json

{
  "eventId": "643eebcfed3d718ca749d9fe"
}

### Add an event to the past events list

PUT http://localhost:5000/proxi-users/add-past-event/%28508%29%20615-7464
Content-Type: application/json

{
  "eventId": "643e189e56f5d5342b0c0c50"
}

###

GET http://localhost:5000/proxi-users/user/643d38c9f0325122c5b6bf7e


###

# Thomas: 643d3e511b8c63707d38ad60, Evan: 643d3e841b8c63707d38ad68, Selwyn: 643d38c9f0325122c5b6bf7e

PUT http://localhost:5000/proxi-users/add-connection/%28508%29%20615-7464
Content-Type: application/json

{
  "connectionId": "643d3e841b8c63707d38ad68"
}

### 

PUT http://localhost:5000/proxi-users/add-skills/%28508%29%20615-7464
Content-Type: application/json

{
  "skills": ["JavaScript", "React", "Node.js"]
}